import { describe, it, expect } from "vitest";
import { promises as fs } from "fs";
import path from "path";

const DEMO_PAGE_PATH = path.join(process.cwd(), "src", "app", "demo", "page.tsx");
const GATE_A2_PAGE_PATH = path.join(process.cwd(), "src", "app", "gate-a2", "page.tsx");
const LAYOUT_PATH = path.join(process.cwd(), "src", "app", "layout.tsx");

describe("Unified product experience (Phase — shared visual system)", () => {
  it("both /demo and /gate-a2 import the shared visual primitives", async () => {
    const demoSource = await fs.readFile(DEMO_PAGE_PATH, "utf-8");
    const gateSource = await fs.readFile(GATE_A2_PAGE_PATH, "utf-8");
    expect(demoSource).toMatch(/from "@\/components\/ui"/);
    expect(gateSource).toMatch(/from "@\/components\/ui"/);
    expect(demoSource).toMatch(/ProductShell/);
    expect(gateSource).toMatch(/ProductShell/);
  });

  it("root metadata no longer says Create Next App", async () => {
    const source = await fs.readFile(LAYOUT_PATH, "utf-8");
    expect(source).not.toMatch(/Create Next App/);
    expect(source).not.toMatch(/Generated by create next app/);
    expect(source).toContain("Still Theirs — Pre-credential safety for agentic commerce");
  });

  it("the local trusted-review action remains available but presented as secondary to the real Linq action", async () => {
    const source = await fs.readFile(DEMO_PAGE_PATH, "utf-8");
    expect(source).toContain("Preview trusted review");
    expect(source).toContain("handleAskTrustedContact");

    // The real Linq action (PrimaryAction) must appear before the local
    // simulation action (SecondaryAction) in source, reflecting its
    // primary/secondary hierarchy.
    const linqButtonIndex = source.indexOf("onClick={handleSendPerspectiveRequest}");
    const previewButtonIndex = source.indexOf("Preview trusted review", linqButtonIndex);
    expect(linqButtonIndex).toBeGreaterThan(-1);
    expect(previewButtonIndex).toBeGreaterThan(linqButtonIndex);
  });

  it("the Linq button remains wired to the existing real handler and endpoint", async () => {
    const source = await fs.readFile(DEMO_PAGE_PATH, "utf-8");
    expect(source).toMatch(/onClick=\{handleSendPerspectiveRequest\}/);
    expect(source).toContain('fetch("/api/linq/trusted-perspective"');
  });

  it("the local trusted-review action remains wired to the existing local simulation, not Linq", async () => {
    const source = await fs.readFile(DEMO_PAGE_PATH, "utf-8");
    expect(source).toMatch(/onClick=\{handleAskTrustedContact\}/);
  });

  it("the trusted-review screens never use guardian/permission/authorization language", async () => {
    const source = await fs.readFile(DEMO_PAGE_PATH, "utf-8");
    const reviewStart = source.indexOf('view === "TRUSTED_REVIEW"');
    const returnEnd = source.indexOf('view === "TRUSTED_RETURN"');
    const trustedSection = source.slice(reviewStart, source.indexOf(")}", returnEnd));
    expect(trustedSection).not.toMatch(/\bguardian\b/i);
    expect(trustedSection).not.toMatch(/\bpermission\b/i);
    expect(trustedSection).not.toMatch(/\bauthorization\b/i);
  });

  it("the demo page never references credential, card, iframe, token, or identifier values (it has no Prava code path at all)", async () => {
    const source = await fs.readFile(DEMO_PAGE_PATH, "utf-8");
    expect(source).not.toMatch(/sessionToken/);
    expect(source).not.toMatch(/iframeUrl/);
    expect(source).not.toMatch(/\bcvv\b/i);
    expect(source).not.toMatch(/\botp\b/i);
    expect(source).not.toMatch(/\bpan\b/i);
  });

  it("the gate-a2 page never renders a card number, CVV, or OTP fixture (the existing dedicated suite already covers iframe/token boundaries in depth)", async () => {
    const source = await fs.readFile(GATE_A2_PAGE_PATH, "utf-8");
    expect(source).not.toMatch(/\bcvv\b/i);
    expect(source).not.toMatch(/\botp\b/i);
    expect(source).not.toMatch(/\bpan\b/i);
  });

  it("APPROVE still displays Gumroad and CA$4.89 by construction (sourced from scenario data, not duplicated literals)", async () => {
    const source = await fs.readFile(DEMO_PAGE_PATH, "utf-8");
    expect(source).toContain("{scenario.merchantLabel}");
    expect(source).toContain("{formatAmount(scenario.amountCents, scenario.currency)}");
  });
});
